apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - agents.smol-agents.ai_agentnodepools.yaml
  - runtime.agents.smol-agents.ai_agents.yaml
  - runtime.agents.smol-agents.ai_tools.yaml
  - runtime.agents.smol-agents.ai_modelproviders.yaml
  - runtime.agents.smol-agents.ai_agentruns.yaml
  - runtime.agents.smol-agents.ai_agentsessions.yaml
  - runtime.agents.smol-agents.ai_agentteams.yaml
  - runtime.agents.smol-agents.ai_eventbindings.yaml
  - runtime.agents.smol-agents.ai_agentworkflows.yaml
  - runtime.agents.smol-agents.ai_agentpolicies.yaml
  - runtime.agents.smol-agents.ai_agentrunquotas.yaml
  - runtime.agents.smol-agents.ai_attachgrants.yaml
  - runtime.agents.smol-agents.ai_agentnetworks.yaml
  - runtime.agents.smol-agents.ai_dynamiccredentialbackends.yaml
  - runtime.agents.smol-agents.ai_modelgateways.yaml
  - runtime.agents.smol-agents.ai_memorystores.yaml
  - runtime.agents.smol-agents.ai_memoryretrievers.yaml
