// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: retrieval.proto

// Package retrieval is the internal gRPC API between the memory-mcp gateway
// (client) and the retrieval workers (server).
//
// Wire format: gRPC over mTLS (steering requirement). Every request carries a
// RequestIdentity so the worker can perform defence-in-depth re-checks
// (R-MEM-WORK-1, R-MEM-AUTH-1). Errors are surfaced as gRPC status codes
// mapped to the memory.Kind typed error set (R-MEM-SEC-1 fail-closed).
//
// Generated Go: pkg/memory/api/grpc/ via buf.gen.yaml.
//   buf generate     (from pkg/memory/api/)

package retrievalpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RetrievalService_Retrieve_FullMethodName       = "/retrieval.v1.RetrievalService/Retrieve"
	RetrievalService_Write_FullMethodName          = "/retrieval.v1.RetrievalService/Write"
	RetrievalService_Get_FullMethodName            = "/retrieval.v1.RetrievalService/Get"
	RetrievalService_Delete_FullMethodName         = "/retrieval.v1.RetrievalService/Delete"
	RetrievalService_ListNamespaces_FullMethodName = "/retrieval.v1.RetrievalService/ListNamespaces"
	RetrievalService_Summarize_FullMethodName      = "/retrieval.v1.RetrievalService/Summarize"
	RetrievalService_BranchFS_FullMethodName       = "/retrieval.v1.RetrievalService/BranchFS"
	RetrievalService_SnapshotFS_FullMethodName     = "/retrieval.v1.RetrievalService/SnapshotFS"
	RetrievalService_ListBranches_FullMethodName   = "/retrieval.v1.RetrievalService/ListBranches"
)

// RetrievalServiceClient is the client API for RetrievalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RetrievalService is the internal gRPC service implemented by retrieval workers
// and called by the memory-mcp gateway. It mirrors the api.RetrievalService Go
// interface exactly; the generated Go client/server satisfy that interface via
// the adapter layer in pkg/memory/api/grpc/adapter.go.
type RetrievalServiceClient interface {
	Retrieve(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*RetrieveResponse, error)
	Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	ListNamespaces(ctx context.Context, in *ListNamespacesRequest, opts ...grpc.CallOption) (*ListNamespacesResponse, error)
	Summarize(ctx context.Context, in *SummarizeRequest, opts ...grpc.CallOption) (*SummarizeResponse, error)
	BranchFS(ctx context.Context, in *BranchFSRequest, opts ...grpc.CallOption) (*BranchFSResponse, error)
	SnapshotFS(ctx context.Context, in *SnapshotFSRequest, opts ...grpc.CallOption) (*SnapshotFSResponse, error)
	ListBranches(ctx context.Context, in *ListBranchesRequest, opts ...grpc.CallOption) (*ListBranchesResponse, error)
}

type retrievalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRetrievalServiceClient(cc grpc.ClientConnInterface) RetrievalServiceClient {
	return &retrievalServiceClient{cc}
}

func (c *retrievalServiceClient) Retrieve(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*RetrieveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveResponse)
	err := c.cc.Invoke(ctx, RetrievalService_Retrieve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *retrievalServiceClient) Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteResponse)
	err := c.cc.Invoke(ctx, RetrievalService_Write_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *retrievalServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, RetrievalService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *retrievalServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, RetrievalService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *retrievalServiceClient) ListNamespaces(ctx context.Context, in *ListNamespacesRequest, opts ...grpc.CallOption) (*ListNamespacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNamespacesResponse)
	err := c.cc.Invoke(ctx, RetrievalService_ListNamespaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *retrievalServiceClient) Summarize(ctx context.Context, in *SummarizeRequest, opts ...grpc.CallOption) (*SummarizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SummarizeResponse)
	err := c.cc.Invoke(ctx, RetrievalService_Summarize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *retrievalServiceClient) BranchFS(ctx context.Context, in *BranchFSRequest, opts ...grpc.CallOption) (*BranchFSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BranchFSResponse)
	err := c.cc.Invoke(ctx, RetrievalService_BranchFS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *retrievalServiceClient) SnapshotFS(ctx context.Context, in *SnapshotFSRequest, opts ...grpc.CallOption) (*SnapshotFSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotFSResponse)
	err := c.cc.Invoke(ctx, RetrievalService_SnapshotFS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *retrievalServiceClient) ListBranches(ctx context.Context, in *ListBranchesRequest, opts ...grpc.CallOption) (*ListBranchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBranchesResponse)
	err := c.cc.Invoke(ctx, RetrievalService_ListBranches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RetrievalServiceServer is the server API for RetrievalService service.
// All implementations should embed UnimplementedRetrievalServiceServer
// for forward compatibility.
//
// RetrievalService is the internal gRPC service implemented by retrieval workers
// and called by the memory-mcp gateway. It mirrors the api.RetrievalService Go
// interface exactly; the generated Go client/server satisfy that interface via
// the adapter layer in pkg/memory/api/grpc/adapter.go.
type RetrievalServiceServer interface {
	Retrieve(context.Context, *RetrieveRequest) (*RetrieveResponse, error)
	Write(context.Context, *WriteRequest) (*WriteResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	ListNamespaces(context.Context, *ListNamespacesRequest) (*ListNamespacesResponse, error)
	Summarize(context.Context, *SummarizeRequest) (*SummarizeResponse, error)
	BranchFS(context.Context, *BranchFSRequest) (*BranchFSResponse, error)
	SnapshotFS(context.Context, *SnapshotFSRequest) (*SnapshotFSResponse, error)
	ListBranches(context.Context, *ListBranchesRequest) (*ListBranchesResponse, error)
}

// UnimplementedRetrievalServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRetrievalServiceServer struct{}

func (UnimplementedRetrievalServiceServer) Retrieve(context.Context, *RetrieveRequest) (*RetrieveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Retrieve not implemented")
}
func (UnimplementedRetrievalServiceServer) Write(context.Context, *WriteRequest) (*WriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedRetrievalServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedRetrievalServiceServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedRetrievalServiceServer) ListNamespaces(context.Context, *ListNamespacesRequest) (*ListNamespacesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNamespaces not implemented")
}
func (UnimplementedRetrievalServiceServer) Summarize(context.Context, *SummarizeRequest) (*SummarizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Summarize not implemented")
}
func (UnimplementedRetrievalServiceServer) BranchFS(context.Context, *BranchFSRequest) (*BranchFSResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BranchFS not implemented")
}
func (UnimplementedRetrievalServiceServer) SnapshotFS(context.Context, *SnapshotFSRequest) (*SnapshotFSResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SnapshotFS not implemented")
}
func (UnimplementedRetrievalServiceServer) ListBranches(context.Context, *ListBranchesRequest) (*ListBranchesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBranches not implemented")
}
func (UnimplementedRetrievalServiceServer) testEmbeddedByValue() {}

// UnsafeRetrievalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RetrievalServiceServer will
// result in compilation errors.
type UnsafeRetrievalServiceServer interface {
	mustEmbedUnimplementedRetrievalServiceServer()
}

func RegisterRetrievalServiceServer(s grpc.ServiceRegistrar, srv RetrievalServiceServer) {
	// If the following call panics, it indicates UnimplementedRetrievalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RetrievalService_ServiceDesc, srv)
}

func _RetrievalService_Retrieve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrievalServiceServer).Retrieve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RetrievalService_Retrieve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrievalServiceServer).Retrieve(ctx, req.(*RetrieveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RetrievalService_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrievalServiceServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RetrievalService_Write_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrievalServiceServer).Write(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RetrievalService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrievalServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RetrievalService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrievalServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RetrievalService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrievalServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RetrievalService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrievalServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RetrievalService_ListNamespaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNamespacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrievalServiceServer).ListNamespaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RetrievalService_ListNamespaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrievalServiceServer).ListNamespaces(ctx, req.(*ListNamespacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RetrievalService_Summarize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummarizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrievalServiceServer).Summarize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RetrievalService_Summarize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrievalServiceServer).Summarize(ctx, req.(*SummarizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RetrievalService_BranchFS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BranchFSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrievalServiceServer).BranchFS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RetrievalService_BranchFS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrievalServiceServer).BranchFS(ctx, req.(*BranchFSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RetrievalService_SnapshotFS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotFSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrievalServiceServer).SnapshotFS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RetrievalService_SnapshotFS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrievalServiceServer).SnapshotFS(ctx, req.(*SnapshotFSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RetrievalService_ListBranches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBranchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrievalServiceServer).ListBranches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RetrievalService_ListBranches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrievalServiceServer).ListBranches(ctx, req.(*ListBranchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RetrievalService_ServiceDesc is the grpc.ServiceDesc for RetrievalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RetrievalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "retrieval.v1.RetrievalService",
	HandlerType: (*RetrievalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Retrieve",
			Handler:    _RetrievalService_Retrieve_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _RetrievalService_Write_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _RetrievalService_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _RetrievalService_Delete_Handler,
		},
		{
			MethodName: "ListNamespaces",
			Handler:    _RetrievalService_ListNamespaces_Handler,
		},
		{
			MethodName: "Summarize",
			Handler:    _RetrievalService_Summarize_Handler,
		},
		{
			MethodName: "BranchFS",
			Handler:    _RetrievalService_BranchFS_Handler,
		},
		{
			MethodName: "SnapshotFS",
			Handler:    _RetrievalService_SnapshotFS_Handler,
		},
		{
			MethodName: "ListBranches",
			Handler:    _RetrievalService_ListBranches_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "retrieval.proto",
}
