// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: retrieval.proto

// Package retrieval is the internal gRPC API between the memory-mcp gateway
// (client) and the retrieval workers (server).
//
// Wire format: gRPC over mTLS (steering requirement). Every request carries a
// RequestIdentity so the worker can perform defence-in-depth re-checks
// (R-MEM-WORK-1, R-MEM-AUTH-1). Errors are surfaced as gRPC status codes
// mapped to the memory.Kind typed error set (R-MEM-SEC-1 fail-closed).
//
// Generated Go: pkg/memory/api/grpc/ via buf.gen.yaml.
//   buf generate     (from pkg/memory/api/)

package retrievalpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RequestIdentity carries the gateway-derived identity fields included in
// every worker request. The worker validates these before dispatching.
type RequestIdentity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tenant is derived from the caller's SPIFFE identity by the gateway.
	Tenant string `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	// namespace is the memory namespace the operation targets.
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// caller_spiffe_id is the full SPIFFE URI of the authenticated caller.
	CallerSpiffeId string `protobuf:"bytes,3,opt,name=caller_spiffe_id,json=callerSpiffeId,proto3" json:"caller_spiffe_id,omitempty"`
	// retriever_ref is the namespace-qualified name of the MemoryRetriever CR
	// (e.g. "team-alpha/prod-knowledge").
	RetrieverRef  string `protobuf:"bytes,4,opt,name=retriever_ref,json=retrieverRef,proto3" json:"retriever_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestIdentity) Reset() {
	*x = RequestIdentity{}
	mi := &file_retrieval_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestIdentity) ProtoMessage() {}

func (x *RequestIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestIdentity.ProtoReflect.Descriptor instead.
func (*RequestIdentity) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{0}
}

func (x *RequestIdentity) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *RequestIdentity) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RequestIdentity) GetCallerSpiffeId() string {
	if x != nil {
		return x.CallerSpiffeId
	}
	return ""
}

func (x *RequestIdentity) GetRetrieverRef() string {
	if x != nil {
		return x.RetrieverRef
	}
	return ""
}

// Document is the atomic unit of storage across all backend kinds.
type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Tenant        string                 `protobuf:"bytes,3,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Content       []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Path          string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Embedding     []float32              `protobuf:"fixed32,7,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	Version       string                 `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,9,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	UpdatedAtUnix int64                  `protobuf:"varint,10,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_retrieval_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{1}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Document) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *Document) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Document) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Document) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Document) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *Document) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Document) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *Document) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

// Chunk is a sub-document produced by the chunking stage.
type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Embedding     []float32              `protobuf:"fixed32,3,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	DocumentId    string                 `protobuf:"bytes,4,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	StartByte     int32                  `protobuf:"varint,5,opt,name=start_byte,json=startByte,proto3" json:"start_byte,omitempty"`
	EndByte       int32                  `protobuf:"varint,6,opt,name=end_byte,json=endByte,proto3" json:"end_byte,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_retrieval_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{2}
}

func (x *Chunk) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Chunk) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Chunk) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *Chunk) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *Chunk) GetStartByte() int32 {
	if x != nil {
		return x.StartByte
	}
	return 0
}

func (x *Chunk) GetEndByte() int32 {
	if x != nil {
		return x.EndByte
	}
	return 0
}

// ScoredChunk pairs a Chunk with its relevance score.
type ScoredChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         *Chunk                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoredChunk) Reset() {
	*x = ScoredChunk{}
	mi := &file_retrieval_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoredChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoredChunk) ProtoMessage() {}

func (x *ScoredChunk) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoredChunk.ProtoReflect.Descriptor instead.
func (*ScoredChunk) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{3}
}

func (x *ScoredChunk) GetChunk() *Chunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *ScoredChunk) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

// Filter carries predicate pushdown hints.
type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Tenant        string                 `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_retrieval_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{4}
}

func (x *Filter) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Filter) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *Filter) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// BranchInfo describes one branch in a filesystem store.
type BranchInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Base            string                 `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	CreatedAtUnix   int64                  `protobuf:"varint,3,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	CommittedAtUnix int64                  `protobuf:"varint,4,opt,name=committed_at_unix,json=committedAtUnix,proto3" json:"committed_at_unix,omitempty"`
	DiscardedAtUnix int64                  `protobuf:"varint,5,opt,name=discarded_at_unix,json=discardedAtUnix,proto3" json:"discarded_at_unix,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BranchInfo) Reset() {
	*x = BranchInfo{}
	mi := &file_retrieval_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BranchInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BranchInfo) ProtoMessage() {}

func (x *BranchInfo) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BranchInfo.ProtoReflect.Descriptor instead.
func (*BranchInfo) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{5}
}

func (x *BranchInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BranchInfo) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *BranchInfo) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *BranchInfo) GetCommittedAtUnix() int64 {
	if x != nil {
		return x.CommittedAtUnix
	}
	return 0
}

func (x *BranchInfo) GetDiscardedAtUnix() int64 {
	if x != nil {
		return x.DiscardedAtUnix
	}
	return 0
}

// SnapshotInfo describes a point-in-time snapshot of a filesystem branch.
type SnapshotInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Branch        string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,3,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotInfo) Reset() {
	*x = SnapshotInfo{}
	mi := &file_retrieval_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotInfo) ProtoMessage() {}

func (x *SnapshotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotInfo.ProtoReflect.Descriptor instead.
func (*SnapshotInfo) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{6}
}

func (x *SnapshotInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SnapshotInfo) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *SnapshotInfo) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *SnapshotInfo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type RetrieveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *RequestIdentity       `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	TopK          int32                  `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Filters       *Filter                `protobuf:"bytes,4,opt,name=filters,proto3" json:"filters,omitempty"`
	StoreRef      string                 `protobuf:"bytes,5,opt,name=store_ref,json=storeRef,proto3" json:"store_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveRequest) Reset() {
	*x = RetrieveRequest{}
	mi := &file_retrieval_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRequest) ProtoMessage() {}

func (x *RetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRequest.ProtoReflect.Descriptor instead.
func (*RetrieveRequest) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{7}
}

func (x *RetrieveRequest) GetIdentity() *RequestIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *RetrieveRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RetrieveRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *RetrieveRequest) GetFilters() *Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *RetrieveRequest) GetStoreRef() string {
	if x != nil {
		return x.StoreRef
	}
	return ""
}

type RetrieveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []*ScoredChunk         `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveResponse) Reset() {
	*x = RetrieveResponse{}
	mi := &file_retrieval_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveResponse) ProtoMessage() {}

func (x *RetrieveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveResponse.ProtoReflect.Descriptor instead.
func (*RetrieveResponse) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{8}
}

func (x *RetrieveResponse) GetChunks() []*ScoredChunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *RetrieveResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *RequestIdentity       `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Document      *Document              `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	Trat          string                 `protobuf:"bytes,3,opt,name=trat,proto3" json:"trat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_retrieval_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{9}
}

func (x *WriteRequest) GetIdentity() *RequestIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *WriteRequest) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *WriteRequest) GetTrat() string {
	if x != nil {
		return x.Trat
	}
	return ""
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_retrieval_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{10}
}

func (x *WriteResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WriteResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *RequestIdentity       `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_retrieval_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{11}
}

func (x *GetRequest) GetIdentity() *RequestIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *GetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *Document              `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_retrieval_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{12}
}

func (x *GetResponse) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *RequestIdentity       `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Trat          string                 `protobuf:"bytes,3,opt,name=trat,proto3" json:"trat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_retrieval_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteRequest) GetIdentity() *RequestIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteRequest) GetTrat() string {
	if x != nil {
		return x.Trat
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_retrieval_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{14}
}

type ListNamespacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *RequestIdentity       `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNamespacesRequest) Reset() {
	*x = ListNamespacesRequest{}
	mi := &file_retrieval_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNamespacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamespacesRequest) ProtoMessage() {}

func (x *ListNamespacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamespacesRequest.ProtoReflect.Descriptor instead.
func (*ListNamespacesRequest) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{15}
}

func (x *ListNamespacesRequest) GetIdentity() *RequestIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type ListNamespacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespaces    []string               `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNamespacesResponse) Reset() {
	*x = ListNamespacesResponse{}
	mi := &file_retrieval_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNamespacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamespacesResponse) ProtoMessage() {}

func (x *ListNamespacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamespacesResponse.ProtoReflect.Descriptor instead.
func (*ListNamespacesResponse) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{16}
}

func (x *ListNamespacesResponse) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

type SummarizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *RequestIdentity       `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeRequest) Reset() {
	*x = SummarizeRequest{}
	mi := &file_retrieval_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeRequest) ProtoMessage() {}

func (x *SummarizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeRequest.ProtoReflect.Descriptor instead.
func (*SummarizeRequest) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{17}
}

func (x *SummarizeRequest) GetIdentity() *RequestIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *SummarizeRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SummarizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeResponse) Reset() {
	*x = SummarizeResponse{}
	mi := &file_retrieval_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeResponse) ProtoMessage() {}

func (x *SummarizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeResponse.ProtoReflect.Descriptor instead.
func (*SummarizeResponse) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{18}
}

func (x *SummarizeResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type BranchFSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *RequestIdentity       `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	BaseBranch    string                 `protobuf:"bytes,2,opt,name=base_branch,json=baseBranch,proto3" json:"base_branch,omitempty"`
	NewBranch     string                 `protobuf:"bytes,3,opt,name=new_branch,json=newBranch,proto3" json:"new_branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BranchFSRequest) Reset() {
	*x = BranchFSRequest{}
	mi := &file_retrieval_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BranchFSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BranchFSRequest) ProtoMessage() {}

func (x *BranchFSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BranchFSRequest.ProtoReflect.Descriptor instead.
func (*BranchFSRequest) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{19}
}

func (x *BranchFSRequest) GetIdentity() *RequestIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *BranchFSRequest) GetBaseBranch() string {
	if x != nil {
		return x.BaseBranch
	}
	return ""
}

func (x *BranchFSRequest) GetNewBranch() string {
	if x != nil {
		return x.NewBranch
	}
	return ""
}

type BranchFSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branch        *BranchInfo            `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BranchFSResponse) Reset() {
	*x = BranchFSResponse{}
	mi := &file_retrieval_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BranchFSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BranchFSResponse) ProtoMessage() {}

func (x *BranchFSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BranchFSResponse.ProtoReflect.Descriptor instead.
func (*BranchFSResponse) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{20}
}

func (x *BranchFSResponse) GetBranch() *BranchInfo {
	if x != nil {
		return x.Branch
	}
	return nil
}

type SnapshotFSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *RequestIdentity       `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Branch        string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotFSRequest) Reset() {
	*x = SnapshotFSRequest{}
	mi := &file_retrieval_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotFSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotFSRequest) ProtoMessage() {}

func (x *SnapshotFSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotFSRequest.ProtoReflect.Descriptor instead.
func (*SnapshotFSRequest) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{21}
}

func (x *SnapshotFSRequest) GetIdentity() *RequestIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *SnapshotFSRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

type SnapshotFSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *SnapshotInfo          `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotFSResponse) Reset() {
	*x = SnapshotFSResponse{}
	mi := &file_retrieval_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotFSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotFSResponse) ProtoMessage() {}

func (x *SnapshotFSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotFSResponse.ProtoReflect.Descriptor instead.
func (*SnapshotFSResponse) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{22}
}

func (x *SnapshotFSResponse) GetSnapshot() *SnapshotInfo {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type ListBranchesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *RequestIdentity       `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBranchesRequest) Reset() {
	*x = ListBranchesRequest{}
	mi := &file_retrieval_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBranchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBranchesRequest) ProtoMessage() {}

func (x *ListBranchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBranchesRequest.ProtoReflect.Descriptor instead.
func (*ListBranchesRequest) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{23}
}

func (x *ListBranchesRequest) GetIdentity() *RequestIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type ListBranchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branches      []*BranchInfo          `protobuf:"bytes,1,rep,name=branches,proto3" json:"branches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBranchesResponse) Reset() {
	*x = ListBranchesResponse{}
	mi := &file_retrieval_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBranchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBranchesResponse) ProtoMessage() {}

func (x *ListBranchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBranchesResponse.ProtoReflect.Descriptor instead.
func (*ListBranchesResponse) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{24}
}

func (x *ListBranchesResponse) GetBranches() []*BranchInfo {
	if x != nil {
		return x.Branches
	}
	return nil
}

var File_retrieval_proto protoreflect.FileDescriptor

const file_retrieval_proto_rawDesc = "" +
	"\n" +
	"\x0fretrieval.proto\x12\fretrieval.v1\"\x96\x01\n" +
	"\x0fRequestIdentity\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12(\n" +
	"\x10caller_spiffe_id\x18\x03 \x01(\tR\x0ecallerSpiffeId\x12#\n" +
	"\rretriever_ref\x18\x04 \x01(\tR\fretrieverRef\"\x85\x03\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06tenant\x18\x03 \x01(\tR\x06tenant\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12@\n" +
	"\bmetadata\x18\x06 \x03(\v2$.retrieval.v1.Document.MetadataEntryR\bmetadata\x12\x1c\n" +
	"\tembedding\x18\a \x03(\x02R\tembedding\x12\x18\n" +
	"\aversion\x18\b \x01(\tR\aversion\x12&\n" +
	"\x0fcreated_at_unix\x18\t \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\n" +
	" \x01(\x03R\rupdatedAtUnix\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaa\x01\n" +
	"\x05Chunk\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1c\n" +
	"\tembedding\x18\x03 \x03(\x02R\tembedding\x12\x1f\n" +
	"\vdocument_id\x18\x04 \x01(\tR\n" +
	"documentId\x12\x1d\n" +
	"\n" +
	"start_byte\x18\x05 \x01(\x05R\tstartByte\x12\x19\n" +
	"\bend_byte\x18\x06 \x01(\x05R\aendByte\"N\n" +
	"\vScoredChunk\x12)\n" +
	"\x05chunk\x18\x01 \x01(\v2\x13.retrieval.v1.ChunkR\x05chunk\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\"\xbb\x01\n" +
	"\x06Filter\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06tenant\x18\x02 \x01(\tR\x06tenant\x12>\n" +
	"\bmetadata\x18\x03 \x03(\v2\".retrieval.v1.Filter.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb4\x01\n" +
	"\n" +
	"BranchInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04base\x18\x02 \x01(\tR\x04base\x12&\n" +
	"\x0fcreated_at_unix\x18\x03 \x01(\x03R\rcreatedAtUnix\x12*\n" +
	"\x11committed_at_unix\x18\x04 \x01(\x03R\x0fcommittedAtUnix\x12*\n" +
	"\x11discarded_at_unix\x18\x05 \x01(\x03R\x0fdiscardedAtUnix\"}\n" +
	"\fSnapshotInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12&\n" +
	"\x0fcreated_at_unix\x18\x03 \x01(\x03R\rcreatedAtUnix\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\"\xc4\x01\n" +
	"\x0fRetrieveRequest\x129\n" +
	"\bidentity\x18\x01 \x01(\v2\x1d.retrieval.v1.RequestIdentityR\bidentity\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\x05R\x04topK\x12.\n" +
	"\afilters\x18\x04 \x01(\v2\x14.retrieval.v1.FilterR\afilters\x12\x1b\n" +
	"\tstore_ref\x18\x05 \x01(\tR\bstoreRef\"[\n" +
	"\x10RetrieveResponse\x121\n" +
	"\x06chunks\x18\x01 \x03(\v2\x19.retrieval.v1.ScoredChunkR\x06chunks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x91\x01\n" +
	"\fWriteRequest\x129\n" +
	"\bidentity\x18\x01 \x01(\v2\x1d.retrieval.v1.RequestIdentityR\bidentity\x122\n" +
	"\bdocument\x18\x02 \x01(\v2\x16.retrieval.v1.DocumentR\bdocument\x12\x12\n" +
	"\x04trat\x18\x03 \x01(\tR\x04trat\"9\n" +
	"\rWriteResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"W\n" +
	"\n" +
	"GetRequest\x129\n" +
	"\bidentity\x18\x01 \x01(\v2\x1d.retrieval.v1.RequestIdentityR\bidentity\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"A\n" +
	"\vGetResponse\x122\n" +
	"\bdocument\x18\x01 \x01(\v2\x16.retrieval.v1.DocumentR\bdocument\"n\n" +
	"\rDeleteRequest\x129\n" +
	"\bidentity\x18\x01 \x01(\v2\x1d.retrieval.v1.RequestIdentityR\bidentity\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04trat\x18\x03 \x01(\tR\x04trat\"\x10\n" +
	"\x0eDeleteResponse\"R\n" +
	"\x15ListNamespacesRequest\x129\n" +
	"\bidentity\x18\x01 \x01(\v2\x1d.retrieval.v1.RequestIdentityR\bidentity\"8\n" +
	"\x16ListNamespacesResponse\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\tR\n" +
	"namespaces\"c\n" +
	"\x10SummarizeRequest\x129\n" +
	"\bidentity\x18\x01 \x01(\v2\x1d.retrieval.v1.RequestIdentityR\bidentity\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\"-\n" +
	"\x11SummarizeResponse\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\"\x8c\x01\n" +
	"\x0fBranchFSRequest\x129\n" +
	"\bidentity\x18\x01 \x01(\v2\x1d.retrieval.v1.RequestIdentityR\bidentity\x12\x1f\n" +
	"\vbase_branch\x18\x02 \x01(\tR\n" +
	"baseBranch\x12\x1d\n" +
	"\n" +
	"new_branch\x18\x03 \x01(\tR\tnewBranch\"D\n" +
	"\x10BranchFSResponse\x120\n" +
	"\x06branch\x18\x01 \x01(\v2\x18.retrieval.v1.BranchInfoR\x06branch\"f\n" +
	"\x11SnapshotFSRequest\x129\n" +
	"\bidentity\x18\x01 \x01(\v2\x1d.retrieval.v1.RequestIdentityR\bidentity\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\"L\n" +
	"\x12SnapshotFSResponse\x126\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x1a.retrieval.v1.SnapshotInfoR\bsnapshot\"P\n" +
	"\x13ListBranchesRequest\x129\n" +
	"\bidentity\x18\x01 \x01(\v2\x1d.retrieval.v1.RequestIdentityR\bidentity\"L\n" +
	"\x14ListBranchesResponse\x124\n" +
	"\bbranches\x18\x01 \x03(\v2\x18.retrieval.v1.BranchInfoR\bbranches2\xbe\x05\n" +
	"\x10RetrievalService\x12I\n" +
	"\bRetrieve\x12\x1d.retrieval.v1.RetrieveRequest\x1a\x1e.retrieval.v1.RetrieveResponse\x12@\n" +
	"\x05Write\x12\x1a.retrieval.v1.WriteRequest\x1a\x1b.retrieval.v1.WriteResponse\x12:\n" +
	"\x03Get\x12\x18.retrieval.v1.GetRequest\x1a\x19.retrieval.v1.GetResponse\x12C\n" +
	"\x06Delete\x12\x1b.retrieval.v1.DeleteRequest\x1a\x1c.retrieval.v1.DeleteResponse\x12[\n" +
	"\x0eListNamespaces\x12#.retrieval.v1.ListNamespacesRequest\x1a$.retrieval.v1.ListNamespacesResponse\x12L\n" +
	"\tSummarize\x12\x1e.retrieval.v1.SummarizeRequest\x1a\x1f.retrieval.v1.SummarizeResponse\x12I\n" +
	"\bBranchFS\x12\x1d.retrieval.v1.BranchFSRequest\x1a\x1e.retrieval.v1.BranchFSResponse\x12O\n" +
	"\n" +
	"SnapshotFS\x12\x1f.retrieval.v1.SnapshotFSRequest\x1a .retrieval.v1.SnapshotFSResponse\x12U\n" +
	"\fListBranches\x12!.retrieval.v1.ListBranchesRequest\x1a\".retrieval.v1.ListBranchesResponseB?Z=github.com/stigen/smol-agents/pkg/memory/api/grpc;retrievalpbb\x06proto3"

var (
	file_retrieval_proto_rawDescOnce sync.Once
	file_retrieval_proto_rawDescData []byte
)

func file_retrieval_proto_rawDescGZIP() []byte {
	file_retrieval_proto_rawDescOnce.Do(func() {
		file_retrieval_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_retrieval_proto_rawDesc), len(file_retrieval_proto_rawDesc)))
	})
	return file_retrieval_proto_rawDescData
}

var file_retrieval_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_retrieval_proto_goTypes = []any{
	(*RequestIdentity)(nil),        // 0: retrieval.v1.RequestIdentity
	(*Document)(nil),               // 1: retrieval.v1.Document
	(*Chunk)(nil),                  // 2: retrieval.v1.Chunk
	(*ScoredChunk)(nil),            // 3: retrieval.v1.ScoredChunk
	(*Filter)(nil),                 // 4: retrieval.v1.Filter
	(*BranchInfo)(nil),             // 5: retrieval.v1.BranchInfo
	(*SnapshotInfo)(nil),           // 6: retrieval.v1.SnapshotInfo
	(*RetrieveRequest)(nil),        // 7: retrieval.v1.RetrieveRequest
	(*RetrieveResponse)(nil),       // 8: retrieval.v1.RetrieveResponse
	(*WriteRequest)(nil),           // 9: retrieval.v1.WriteRequest
	(*WriteResponse)(nil),          // 10: retrieval.v1.WriteResponse
	(*GetRequest)(nil),             // 11: retrieval.v1.GetRequest
	(*GetResponse)(nil),            // 12: retrieval.v1.GetResponse
	(*DeleteRequest)(nil),          // 13: retrieval.v1.DeleteRequest
	(*DeleteResponse)(nil),         // 14: retrieval.v1.DeleteResponse
	(*ListNamespacesRequest)(nil),  // 15: retrieval.v1.ListNamespacesRequest
	(*ListNamespacesResponse)(nil), // 16: retrieval.v1.ListNamespacesResponse
	(*SummarizeRequest)(nil),       // 17: retrieval.v1.SummarizeRequest
	(*SummarizeResponse)(nil),      // 18: retrieval.v1.SummarizeResponse
	(*BranchFSRequest)(nil),        // 19: retrieval.v1.BranchFSRequest
	(*BranchFSResponse)(nil),       // 20: retrieval.v1.BranchFSResponse
	(*SnapshotFSRequest)(nil),      // 21: retrieval.v1.SnapshotFSRequest
	(*SnapshotFSResponse)(nil),     // 22: retrieval.v1.SnapshotFSResponse
	(*ListBranchesRequest)(nil),    // 23: retrieval.v1.ListBranchesRequest
	(*ListBranchesResponse)(nil),   // 24: retrieval.v1.ListBranchesResponse
	nil,                            // 25: retrieval.v1.Document.MetadataEntry
	nil,                            // 26: retrieval.v1.Filter.MetadataEntry
}
var file_retrieval_proto_depIdxs = []int32{
	25, // 0: retrieval.v1.Document.metadata:type_name -> retrieval.v1.Document.MetadataEntry
	2,  // 1: retrieval.v1.ScoredChunk.chunk:type_name -> retrieval.v1.Chunk
	26, // 2: retrieval.v1.Filter.metadata:type_name -> retrieval.v1.Filter.MetadataEntry
	0,  // 3: retrieval.v1.RetrieveRequest.identity:type_name -> retrieval.v1.RequestIdentity
	4,  // 4: retrieval.v1.RetrieveRequest.filters:type_name -> retrieval.v1.Filter
	3,  // 5: retrieval.v1.RetrieveResponse.chunks:type_name -> retrieval.v1.ScoredChunk
	0,  // 6: retrieval.v1.WriteRequest.identity:type_name -> retrieval.v1.RequestIdentity
	1,  // 7: retrieval.v1.WriteRequest.document:type_name -> retrieval.v1.Document
	0,  // 8: retrieval.v1.GetRequest.identity:type_name -> retrieval.v1.RequestIdentity
	1,  // 9: retrieval.v1.GetResponse.document:type_name -> retrieval.v1.Document
	0,  // 10: retrieval.v1.DeleteRequest.identity:type_name -> retrieval.v1.RequestIdentity
	0,  // 11: retrieval.v1.ListNamespacesRequest.identity:type_name -> retrieval.v1.RequestIdentity
	0,  // 12: retrieval.v1.SummarizeRequest.identity:type_name -> retrieval.v1.RequestIdentity
	0,  // 13: retrieval.v1.BranchFSRequest.identity:type_name -> retrieval.v1.RequestIdentity
	5,  // 14: retrieval.v1.BranchFSResponse.branch:type_name -> retrieval.v1.BranchInfo
	0,  // 15: retrieval.v1.SnapshotFSRequest.identity:type_name -> retrieval.v1.RequestIdentity
	6,  // 16: retrieval.v1.SnapshotFSResponse.snapshot:type_name -> retrieval.v1.SnapshotInfo
	0,  // 17: retrieval.v1.ListBranchesRequest.identity:type_name -> retrieval.v1.RequestIdentity
	5,  // 18: retrieval.v1.ListBranchesResponse.branches:type_name -> retrieval.v1.BranchInfo
	7,  // 19: retrieval.v1.RetrievalService.Retrieve:input_type -> retrieval.v1.RetrieveRequest
	9,  // 20: retrieval.v1.RetrievalService.Write:input_type -> retrieval.v1.WriteRequest
	11, // 21: retrieval.v1.RetrievalService.Get:input_type -> retrieval.v1.GetRequest
	13, // 22: retrieval.v1.RetrievalService.Delete:input_type -> retrieval.v1.DeleteRequest
	15, // 23: retrieval.v1.RetrievalService.ListNamespaces:input_type -> retrieval.v1.ListNamespacesRequest
	17, // 24: retrieval.v1.RetrievalService.Summarize:input_type -> retrieval.v1.SummarizeRequest
	19, // 25: retrieval.v1.RetrievalService.BranchFS:input_type -> retrieval.v1.BranchFSRequest
	21, // 26: retrieval.v1.RetrievalService.SnapshotFS:input_type -> retrieval.v1.SnapshotFSRequest
	23, // 27: retrieval.v1.RetrievalService.ListBranches:input_type -> retrieval.v1.ListBranchesRequest
	8,  // 28: retrieval.v1.RetrievalService.Retrieve:output_type -> retrieval.v1.RetrieveResponse
	10, // 29: retrieval.v1.RetrievalService.Write:output_type -> retrieval.v1.WriteResponse
	12, // 30: retrieval.v1.RetrievalService.Get:output_type -> retrieval.v1.GetResponse
	14, // 31: retrieval.v1.RetrievalService.Delete:output_type -> retrieval.v1.DeleteResponse
	16, // 32: retrieval.v1.RetrievalService.ListNamespaces:output_type -> retrieval.v1.ListNamespacesResponse
	18, // 33: retrieval.v1.RetrievalService.Summarize:output_type -> retrieval.v1.SummarizeResponse
	20, // 34: retrieval.v1.RetrievalService.BranchFS:output_type -> retrieval.v1.BranchFSResponse
	22, // 35: retrieval.v1.RetrievalService.SnapshotFS:output_type -> retrieval.v1.SnapshotFSResponse
	24, // 36: retrieval.v1.RetrievalService.ListBranches:output_type -> retrieval.v1.ListBranchesResponse
	28, // [28:37] is the sub-list for method output_type
	19, // [19:28] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_retrieval_proto_init() }
func file_retrieval_proto_init() {
	if File_retrieval_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_retrieval_proto_rawDesc), len(file_retrieval_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_retrieval_proto_goTypes,
		DependencyIndexes: file_retrieval_proto_depIdxs,
		MessageInfos:      file_retrieval_proto_msgTypes,
	}.Build()
	File_retrieval_proto = out.File
	file_retrieval_proto_goTypes = nil
	file_retrieval_proto_depIdxs = nil
}
