apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Service
      group: serving.knative.dev
      version: v1
      name: knative-agents
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations/autoscaling.knative.dev~1min-scale
        value: "0"
