// Package cloud contains the bits shared by every provisioning target
// (aws + hetzner today; baremetal next): the k0s cloud-init script, an SSH
// bootstrap client, kubeconfig rewriting, and host-level networking add-ons
// (Cloudflare Tunnel + WireGuard).
package cloud

import (
	"bytes"
	"fmt"
	"text/template"
)

// CloudInitScript renders the user-data shell script that brings k0s up on a
// fresh host and (optionally) joins the host to a private network so its k8s
// API isn't exposed publicly.
//
// Composition order (deliberate):
//  1. WireGuard install + wg-quick@wg0 (so the API is reachable via the WG IP
//     by the time clients try).
//  2. Tailscale install + `tailscale up` (mesh join before k0s; the node's
//     tailnet IP is then stable for the deploy driver to read back).
//  3. k0s install + start; wait for readyz.
//  4. Cloudflare Tunnel install (cloudflared) after k0s is up: cloudflared
//     dials https://127.0.0.1:6443, so starting it earlier would just retry.
//  5. Sentinel file the deploy driver polls.
//
// Output is a #!/bin/bash script suitable as user-data for both AWS EC2 and
// Hetzner Cloud.
func CloudInitScript(opts CloudInitOptions) (string, error) {
	if opts.SentinelPath == "" {
		opts.SentinelPath = DefaultSentinelPath
	}
	if opts.KubeconfigPath == "" {
		opts.KubeconfigPath = DefaultKubeconfigPath
	}
	// Pre-quote secrets/args: each is interpolated as a single shell argument.
	// Even though current CF tokens / Tailscale keys are alphanumeric, the
	// template shouldn't be load-bearing for that assumption.
	quotedToken := ""
	if opts.CloudflareTunnelToken != "" {
		quotedToken = shellQuote(opts.CloudflareTunnelToken)
	}
	quotedTSKey, quotedTSTags := "", ""
	if opts.TailscaleAuthKey != "" {
		quotedTSKey = shellQuote(opts.TailscaleAuthKey)
	}
	if opts.TailscaleTags != "" {
		quotedTSTags = shellQuote(opts.TailscaleTags)
	}
	type tdata struct {
		CloudInitOptions
		QuotedCloudflareToken  string
		QuotedTailscaleAuthKey string
		QuotedTailscaleTags    string
	}
	var buf bytes.Buffer
	if err := cloudInitTmpl.Execute(&buf, tdata{opts, quotedToken, quotedTSKey, quotedTSTags}); err != nil {
		return "", fmt.Errorf("render cloud-init: %w", err)
	}
	return buf.String(), nil
}

// CloudInitOptions tunes the rendered script.
type CloudInitOptions struct {
	// Hostname: optional; sets node hostname pre-install.
	Hostname string

	// SentinelPath: defaults to DefaultSentinelPath.
	SentinelPath string

	// KubeconfigPath: defaults to DefaultKubeconfigPath.
	KubeconfigPath string

	// CloudflareTunnelToken: non-empty -> install cloudflared as a systemd
	// service with this tunnel token (user must have configured the tunnel
	// with an ingress to https://localhost:6443 in the Cloudflare dashboard).
	CloudflareTunnelToken string

	// WireGuardConfig: non-empty -> install wireguard-tools and write this
	// content verbatim to /etc/wireguard/wg0.conf; enable wg-quick@wg0.
	// Must not contain the literal heredoc delimiter "AGENTCTL_WG_EOF".
	WireGuardConfig string

	// TailscaleAuthKey: non-empty -> install Tailscale and run `tailscale up`
	// with this auth key, joining the host to the tailnet. Prefer an ephemeral
	// auth key so the node de-registers automatically on teardown. Secret:
	// interpolated shell-quoted and never logged.
	TailscaleAuthKey string

	// TailscaleTags: optional comma-separated ACL tags (e.g. "tag:k8s")
	// advertised via `tailscale up --advertise-tags`. Required when the auth
	// key is tagged. Ignored unless TailscaleAuthKey is set.
	TailscaleTags string
}

const (
	// DefaultSentinelPath is the file the deploy driver polls via SSH to
	// know k0s is up and the kubeconfig is fetchable.
	DefaultSentinelPath = "/var/lib/k0s/READY"

	// DefaultKubeconfigPath is where k0s' admin.conf is copied.
	DefaultKubeconfigPath = "/root/admin.conf"
)

var cloudInitTmpl = template.Must(template.New("cloudinit").Parse(`#!/bin/bash
# Generated by agentctl deploy — k0s single-node edge bootstrap.
set -euo pipefail
exec > >(tee /var/log/agentctl-bootstrap.log) 2>&1

{{- if .Hostname }}
hostnamectl set-hostname {{ .Hostname }}
{{- end }}

# Network warmup.
for i in $(seq 1 30); do
  if curl -sSf -o /dev/null https://get.k0s.sh; then break; fi
  sleep 2
done

{{- if .WireGuardConfig }}

# WireGuard — bring up the mesh before k0s so the API is reachable on wg0.
if command -v dnf >/dev/null 2>&1; then
  dnf install -y wireguard-tools iproute
elif command -v apt-get >/dev/null 2>&1; then
  DEBIAN_FRONTEND=noninteractive apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y wireguard wireguard-tools iproute2
else
  echo "unsupported distro: install wireguard-tools manually" >&2; exit 1
fi
install -d -m 0700 /etc/wireguard
cat > /etc/wireguard/wg0.conf <<'AGENTCTL_WG_EOF'
{{ .WireGuardConfig }}
AGENTCTL_WG_EOF
chmod 600 /etc/wireguard/wg0.conf
systemctl enable --now wg-quick@wg0
{{- end }}

{{- if .TailscaleAuthKey }}

# Tailscale — join the tailnet before k0s so the API is reachable on the
# tailnet IP. The install script auto-detects the distro and starts tailscaled.
curl -fsSL https://tailscale.com/install.sh | sh
systemctl enable --now tailscaled
tailscale up --authkey {{ .QuotedTailscaleAuthKey }}{{ if .Hostname }} --hostname {{ .Hostname }}{{ end }}{{ if .TailscaleTags }} --advertise-tags {{ .QuotedTailscaleTags }}{{ end }}
{{- end }}

# Install k0s (OS-agnostic; auto-detects arch).
if ! command -v k0s >/dev/null 2>&1; then
  curl -sSLf https://get.k0s.sh | sh
fi
if ! systemctl is-enabled k0scontroller >/dev/null 2>&1; then
  k0s install controller --single
fi
systemctl enable --now k0scontroller

# Wait for the API to answer.
for i in $(seq 1 120); do
  if [ -f /var/lib/k0s/pki/admin.conf ] && k0s kubectl get --raw=/readyz >/dev/null 2>&1; then
    break
  fi
  sleep 3
done

install -m 0600 /var/lib/k0s/pki/admin.conf {{ .KubeconfigPath }}
chown root:root {{ .KubeconfigPath }}

{{- if .CloudflareTunnelToken }}

# Cloudflare Tunnel — install cloudflared after k0s is up (origin = 127.0.0.1:6443).
arch=$(uname -m)
case "$arch" in
  x86_64)        cfarch=amd64 ;;
  aarch64|arm64) cfarch=arm64 ;;
  *) echo "unsupported arch for cloudflared: $arch" >&2; exit 1 ;;
esac
curl -fsSLo /usr/local/bin/cloudflared \
  "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-${cfarch}"
chmod +x /usr/local/bin/cloudflared
cloudflared service install {{ .QuotedCloudflareToken }}
{{- end }}

touch {{ .SentinelPath }}
echo "agentctl bootstrap complete at $(date -u +%FT%TZ)"
`))
