// Package cloud contains the bits shared by every provisioning target
// (currently aws + hetzner): the k0s cloud-init script, an SSH bootstrap
// client, and kubeconfig rewriting.
//
// V1 ships a single-node k0s edge per target. Kata + devmapper is intentionally
// out of scope here — the hardened recipes for that live under
// scripts/aws-l2/cloud-init-*.tmpl and are a follow-up integration.
package cloud

import (
	"bytes"
	"fmt"
	"text/template"
)

// CloudInitScript renders the user-data shell script that brings k0s up on a
// fresh host. The script:
//   - installs k0s via the upstream installer (OS-agnostic),
//   - registers a single-node controller (controller + worker on the same host),
//   - starts the service and waits until the k8s API answers,
//   - writes the kubeconfig under /root/admin.conf with mode 0600,
//   - drops a SENTINEL file so the deploy driver knows when to fetch.
//
// The output is a `#!/bin/bash` script suitable as user-data for both AWS EC2
// (UserData) and Hetzner Cloud (UserData). The script is intentionally idempotent
// for "rerun-after-reboot" but cloud-init's runcmd only fires once per boot —
// the idempotence is defensive, not load-bearing.
func CloudInitScript(opts CloudInitOptions) (string, error) {
	if opts.SentinelPath == "" {
		opts.SentinelPath = DefaultSentinelPath
	}
	if opts.KubeconfigPath == "" {
		opts.KubeconfigPath = DefaultKubeconfigPath
	}
	var buf bytes.Buffer
	if err := cloudInitTmpl.Execute(&buf, opts); err != nil {
		return "", fmt.Errorf("render cloud-init: %w", err)
	}
	return buf.String(), nil
}

// CloudInitOptions tunes the rendered script. Most callers can leave the
// defaults — only Hostname is usually set.
type CloudInitOptions struct {
	Hostname       string // optional; sets the node hostname pre-install
	SentinelPath   string // default: DefaultSentinelPath
	KubeconfigPath string // default: DefaultKubeconfigPath
}

const (
	// DefaultSentinelPath is the file the deploy driver polls via SSH to
	// know k0s is up and the kubeconfig is fetchable.
	DefaultSentinelPath = "/var/lib/k0s/READY"

	// DefaultKubeconfigPath is where k0s' admin.conf is copied to. The
	// driver SSH-reads this file and rewrites the server URL with the
	// instance's public IP.
	DefaultKubeconfigPath = "/root/admin.conf"
)

var cloudInitTmpl = template.Must(template.New("cloudinit").Parse(`#!/bin/bash
# Generated by agentctl deploy — k0s single-node edge bootstrap.
set -euo pipefail
exec > >(tee /var/log/agentctl-bootstrap.log) 2>&1

{{- if .Hostname }}
hostnamectl set-hostname {{ .Hostname }}
{{- end }}

# Wait for the network to settle; cloud-init kicks off very early on some images.
for i in $(seq 1 30); do
  if curl -sSf -o /dev/null https://get.k0s.sh; then break; fi
  sleep 2
done

# Install the k0s binary + systemd unit (OS-agnostic; auto-detects arch).
if ! command -v k0s >/dev/null 2>&1; then
  curl -sSLf https://get.k0s.sh | sh
fi

# Single-node controller = controller + worker on the same host. Idempotent.
if ! systemctl is-enabled k0scontroller >/dev/null 2>&1; then
  k0s install controller --single
fi
systemctl enable --now k0scontroller

# Wait for the kube-apiserver to answer locally (admin.conf appears slightly
# later than systemd Active=running).
for i in $(seq 1 120); do
  if [ -f /var/lib/k0s/pki/admin.conf ] && k0s kubectl get --raw=/readyz >/dev/null 2>&1; then
    break
  fi
  sleep 3
done

install -m 0600 /var/lib/k0s/pki/admin.conf {{ .KubeconfigPath }}
chown root:root {{ .KubeconfigPath }}

# Sentinel: the deploy driver polls 'test -f' on this path over SSH.
touch {{ .SentinelPath }}
echo "agentctl bootstrap complete at $(date -u +%FT%TZ)"
`))
