apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smol-agents
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - cluster-spiffe-id.yaml
  - knative-service.yaml
commonLabels:
  app.kubernetes.io/name: smol-agents
  app.kubernetes.io/managed-by: kustomize
