// Package builders — secret_broker.go
//
// AttachSecretBroker injects the secret-proxy broker sidecar into an AgentRun
// pod so `agent run` can lease harness env secretRef values at runtime. It uses
// the no-SPIRE local (SO_PEERCRED uid) attestation mode — the run pod needs no
// SPIRE CSI socket. The per-run broker config Secret (static backend + policy)
// is generated by the controller (BuildBrokerConfigSecret).
//
// The broker is a *native sidecar* (init container with restartPolicy=Always,
// k8s ≥ 1.29 stable in 1.33): k8s starts it before the main run container and
// sends it SIGTERM when the main container exits — so the pod transitions to
// Succeeded/Failed naturally and the controller's pod-phase fold trigger fires.
// A regular sidecar (long-running container) would keep the pod Phase=Running
// forever after the agent exited, stranding AgentRun.Status.
package builders

import (
	"fmt"
	"sort"

	"gopkg.in/yaml.v3"
	corev1 "k8s.io/api/core/v1"
	resource "k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/utils/ptr"

	amv1 "github.com/smol-platform/smol-agents/operator/api/agentmodel/v1"
	"github.com/smol-platform/smol-agents/pkg/secrets"
)

const (
	secretBrokerVolumeName = "secret-broker"
	brokerConfigVolumeName = "broker-config"
	brokerSocketDir        = "/run/secret-broker"
	secretProxyName        = "secret-proxy"

	// RunPodUID is the uid AgentRun pods run as (see BuildAgentRunPod's
	// PodSecurityContext). The local broker authorizes this uid.
	RunPodUID int64 = 65532
)

// BrokerConfigSecretName is the per-run broker config Secret name.
func BrokerConfigSecretName(runName string) string { return runName + "-broker" }

// AttachSecretBroker adds the secret-broker UDS volume, the broker-config Secret
// volume, and the secret-proxy sidecar, and mounts the UDS into the execution
// container (index 0) so it can lease secrets. The broker UDS is NOT mounted
// into other sidecars (agentfs/memory), keeping the lease surface to the agent.
// The sidecar is *native* (init container with restartPolicy=Always) so it
// starts before the main container and is terminated when the main container
// exits, letting the pod transition to a terminal phase. Idempotent.
func AttachSecretBroker(pod *corev1.Pod, runName string) *corev1.Pod {
	// Native sidecars live in InitContainers; check there for idempotency.
	for _, c := range pod.Spec.InitContainers {
		if c.Name == secretProxyName {
			return pod
		}
	}

	pod.Spec.Volumes = append(pod.Spec.Volumes,
		corev1.Volume{
			Name:         secretBrokerVolumeName,
			VolumeSource: corev1.VolumeSource{EmptyDir: &corev1.EmptyDirVolumeSource{}},
		},
		corev1.Volume{
			Name: brokerConfigVolumeName,
			VolumeSource: corev1.VolumeSource{
				Secret: &corev1.SecretVolumeSource{SecretName: BrokerConfigSecretName(runName)},
			},
		},
	)

	// The execution container dials the broker UDS.
	pod.Spec.Containers[0].VolumeMounts = append(pod.Spec.Containers[0].VolumeMounts,
		corev1.VolumeMount{Name: secretBrokerVolumeName, MountPath: brokerSocketDir})

	// Prepend so the broker starts before any (regular) init container that
	// might already be there — and well before the main container.
	pod.Spec.InitContainers = append([]corev1.Container{secretProxyRunContainer()}, pod.Spec.InitContainers...)
	return pod
}

// brokerConfigYAML mirrors cmd/secret-proxy's brokerConfig (yaml tags must
// match its parser). Only the fields the local-mode run broker needs.
type brokerConfigYAML struct {
	SocketPath       string `yaml:"socketPath"`
	PeerAuth         string `yaml:"peerAuth"`
	LocalTrustDomain string `yaml:"localTrustDomain,omitempty"`
	Backend          struct {
		Kind   string         `yaml:"kind"`
		Static []brokerStatic `yaml:"static"`
	} `yaml:"backend"`
	Policy []brokerPolicy `yaml:"policy"`
}

type brokerStatic struct {
	SPIFFEID string            `yaml:"spiffeID"`
	Items    map[string]string `yaml:"items"`
}

type brokerPolicy struct {
	SPIFFEID string   `yaml:"spiffeID"`
	Allow    []string `yaml:"allow"`
}

// BuildBrokerConfigSecret renders the run's secret-proxy config: a static
// backend holding the resolved secret values + a policy, both keyed to the run
// pod's local identity (spiffe://<local-td>/uid/<RunPodUID>) so LocalPeerAttestor
// authorizes the agent. values maps the lease name (== harness env
// secretRef.SecretName) to the resolved bytes. The result is a Secret (it holds
// values), mounted into the secret-proxy at /etc/secret-proxy/config.yaml.
func BuildBrokerConfigSecret(run *amv1.AgentRun, values map[string][]byte) (*corev1.Secret, error) {
	id, err := secrets.LocalIDForUID("", uint32(RunPodUID))
	if err != nil {
		return nil, fmt.Errorf("local identity: %w", err)
	}
	items := make(map[string]string, len(values))
	allow := make([]string, 0, len(values))
	for name, val := range values {
		items[name] = string(val)
		allow = append(allow, name)
	}
	sort.Strings(allow)

	var cfg brokerConfigYAML
	cfg.SocketPath = brokerSocketDir + "/secret-broker.sock"
	cfg.PeerAuth = "local"
	cfg.Backend.Kind = "static"
	cfg.Backend.Static = []brokerStatic{{SPIFFEID: id.String(), Items: items}}
	cfg.Policy = []brokerPolicy{{SPIFFEID: id.String(), Allow: allow}}

	raw, err := yaml.Marshal(cfg)
	if err != nil {
		return nil, fmt.Errorf("marshal broker config: %w", err)
	}
	return &corev1.Secret{
		TypeMeta: metav1.TypeMeta{APIVersion: "v1", Kind: "Secret"},
		ObjectMeta: metav1.ObjectMeta{
			Name:      BrokerConfigSecretName(run.Name),
			Namespace: run.Namespace,
			Labels: map[string]string{
				"app.kubernetes.io/name":      "smol-agents",
				"app.kubernetes.io/component": "agent-run",
				"agents.smol-agents.ai/run":   run.Name,
			},
		},
		Data: map[string][]byte{"config.yaml": raw},
	}, nil
}

func secretProxyRunContainer() corev1.Container {
	return corev1.Container{
		Name:            secretProxyName,
		Image:           SecretProxyImage(),
		ImagePullPolicy: corev1.PullIfNotPresent,
		Args:            []string{"--config=/etc/secret-proxy/config.yaml"},
		// RestartPolicy=Always (combined with placement in InitContainers) is
		// what marks this as a native sidecar: k8s starts it before regular
		// containers and SIGTERMs it when the last regular container exits, so
		// the pod transitions to Succeeded/Failed instead of getting stuck.
		RestartPolicy: ptr.To(corev1.ContainerRestartPolicyAlways),
		SecurityContext: &corev1.SecurityContext{
			AllowPrivilegeEscalation: ptr.To(false),
			ReadOnlyRootFilesystem:   ptr.To(true),
			RunAsNonRoot:             ptr.To(true),
			Capabilities:             &corev1.Capabilities{Drop: []corev1.Capability{"ALL"}},
		},
		Resources: corev1.ResourceRequirements{
			Limits: corev1.ResourceList{
				corev1.ResourceCPU:    resource.MustParse("200m"),
				corev1.ResourceMemory: resource.MustParse("128Mi"),
			},
			Requests: corev1.ResourceList{
				corev1.ResourceCPU:    resource.MustParse("50m"),
				corev1.ResourceMemory: resource.MustParse("64Mi"),
			},
		},
		VolumeMounts: []corev1.VolumeMount{
			{Name: secretBrokerVolumeName, MountPath: brokerSocketDir},
			{Name: brokerConfigVolumeName, MountPath: "/etc/secret-proxy", ReadOnly: true},
		},
	}
}
