//go:build !ignore_autogenerated

// Copyright Stigen.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanaryConfig) DeepCopyInto(out *CanaryConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanaryConfig.
func (in *CanaryConfig) DeepCopy() *CanaryConfig {
	if in == nil {
		return nil
	}
	out := new(CanaryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EBPFFeature) DeepCopyInto(out *EBPFFeature) {
	*out = *in
	out.FeatureBase = in.FeatureBase
	if in.Programs != nil {
		in, out := &in.Programs, &out.Programs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EBPFFeature.
func (in *EBPFFeature) DeepCopy() *EBPFFeature {
	if in == nil {
		return nil
	}
	out := new(EBPFFeature)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EBPFLoaderSpec) DeepCopyInto(out *EBPFLoaderSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EBPFLoaderSpec.
func (in *EBPFLoaderSpec) DeepCopy() *EBPFLoaderSpec {
	if in == nil {
		return nil
	}
	out := new(EBPFLoaderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureBase) DeepCopyInto(out *FeatureBase) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureBase.
func (in *FeatureBase) DeepCopy() *FeatureBase {
	if in == nil {
		return nil
	}
	out := new(FeatureBase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeaturePolicyRow) DeepCopyInto(out *FeaturePolicyRow) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeaturePolicyRow.
func (in *FeaturePolicyRow) DeepCopy() *FeaturePolicyRow {
	if in == nil {
		return nil
	}
	out := new(FeaturePolicyRow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureStatus) DeepCopyInto(out *FeatureStatus) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureStatus.
func (in *FeatureStatus) DeepCopy() *FeatureStatus {
	if in == nil {
		return nil
	}
	out := new(FeatureStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Features) DeepCopyInto(out *Features) {
	*out = *in
	out.Identity = in.Identity
	in.Transport.DeepCopyInto(&out.Transport)
	out.Secrets = in.Secrets
	out.Sandbox = in.Sandbox
	in.EBPF.DeepCopyInto(&out.EBPF)
	out.Knative = in.Knative
	out.Observability = in.Observability
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Features.
func (in *Features) DeepCopy() *Features {
	if in == nil {
		return nil
	}
	out := new(Features)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityFeature) DeepCopyInto(out *IdentityFeature) {
	*out = *in
	out.FeatureBase = in.FeatureBase
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityFeature.
func (in *IdentityFeature) DeepCopy() *IdentityFeature {
	if in == nil {
		return nil
	}
	out := new(IdentityFeature)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnativeAgent) DeepCopyInto(out *KnativeAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnativeAgent.
func (in *KnativeAgent) DeepCopy() *KnativeAgent {
	if in == nil {
		return nil
	}
	out := new(KnativeAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KnativeAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnativeAgentList) DeepCopyInto(out *KnativeAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KnativeAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnativeAgentList.
func (in *KnativeAgentList) DeepCopy() *KnativeAgentList {
	if in == nil {
		return nil
	}
	out := new(KnativeAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KnativeAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnativeAgentPlatformSpec.
func (in *KnativeAgentPlatformSpec) DeepCopy() *KnativeAgentPlatformSpec {
	if in == nil {
		return nil
	}
	out := new(KnativeAgentPlatformSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnativeAgentPlatformStatus.
func (in *KnativeAgentPlatformStatus) DeepCopy() *KnativeAgentPlatformStatus {
	if in == nil {
		return nil
	}
	out := new(KnativeAgentPlatformStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnativeAgentSpec) DeepCopyInto(out *KnativeAgentSpec) {
	*out = *in
	in.Features.DeepCopyInto(&out.Features)
	out.Rollout = in.Rollout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnativeAgentSpec.
func (in *KnativeAgentSpec) DeepCopy() *KnativeAgentSpec {
	if in == nil {
		return nil
	}
	out := new(KnativeAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnativeAgentStatus) DeepCopyInto(out *KnativeAgentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = make(map[string]FeatureStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnativeAgentStatus.
func (in *KnativeAgentStatus) DeepCopy() *KnativeAgentStatus {
	if in == nil {
		return nil
	}
	out := new(KnativeAgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnativeFeature) DeepCopyInto(out *KnativeFeature) {
	*out = *in
	out.FeatureBase = in.FeatureBase
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnativeFeature.
func (in *KnativeFeature) DeepCopy() *KnativeFeature {
	if in == nil {
		return nil
	}
	out := new(KnativeFeature)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservabilityFeature) DeepCopyInto(out *ObservabilityFeature) {
	*out = *in
	out.FeatureBase = in.FeatureBase
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservabilityFeature.
func (in *ObservabilityFeature) DeepCopy() *ObservabilityFeature {
	if in == nil {
		return nil
	}
	out := new(ObservabilityFeature)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutPolicy) DeepCopyInto(out *RolloutPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutPolicy.
func (in *RolloutPolicy) DeepCopy() *RolloutPolicy {
	if in == nil {
		return nil
	}
	out := new(RolloutPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxFeature) DeepCopyInto(out *SandboxFeature) {
	*out = *in
	out.FeatureBase = in.FeatureBase
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxFeature.
func (in *SandboxFeature) DeepCopy() *SandboxFeature {
	if in == nil {
		return nil
	}
	out := new(SandboxFeature)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretsFeature) DeepCopyInto(out *SecretsFeature) {
	*out = *in
	out.FeatureBase = in.FeatureBase
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretsFeature.
func (in *SecretsFeature) DeepCopy() *SecretsFeature {
	if in == nil {
		return nil
	}
	out := new(SecretsFeature)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportFeature) DeepCopyInto(out *TransportFeature) {
	*out = *in
	in.Private.DeepCopyInto(&out.Private)
	out.Public = in.Public
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportFeature.
func (in *TransportFeature) DeepCopy() *TransportFeature {
	if in == nil {
		return nil
	}
	out := new(TransportFeature)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportPrivateFeature) DeepCopyInto(out *TransportPrivateFeature) {
	*out = *in
	out.FeatureBase = in.FeatureBase
	if in.Authorize != nil {
		in, out := &in.Authorize, &out.Authorize
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportPrivateFeature.
func (in *TransportPrivateFeature) DeepCopy() *TransportPrivateFeature {
	if in == nil {
		return nil
	}
	out := new(TransportPrivateFeature)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportPublicFeature) DeepCopyInto(out *TransportPublicFeature) {
	*out = *in
	out.FeatureBase = in.FeatureBase
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportPublicFeature.
func (in *TransportPublicFeature) DeepCopy() *TransportPublicFeature {
	if in == nil {
		return nil
	}
	out := new(TransportPublicFeature)
	in.DeepCopyInto(out)
	return out
}
